// Generated by CoffeeScript 1.6.2
(function() {
  define(["app", "modules/home", "modules/source"], function(app, Home, Source) {
    var Router;

    Router = Backbone.Router.extend({
      routes: {
        "source": "source",
        "": "index"
      },
      index: function(hash) {
        var fields;

        console.log('index of home');
        fields = [
          {
            name: "source"
          }, {
            name: "files"
          }
        ];
        return app.useLayout('main').setViews({
          '.tutorial': new Home.Views.Tutorial(fields)
        }).render();
      },
      source: function() {
        var collection;

        collection = [
          {
            name: "nginx",
            version: "1.2.4",
            url: "http://nginx-1.2.4"
          }, {
            name: "nginx",
            version: "1.3.4",
            url: "http://nginx-1.3.4"
          }, {
            name: "httpd",
            version: "1.2.4",
            url: "http://httpd-1.2.4"
          }
        ];
        console.log('index of source');
        return app.useLayout('main').setViews({
          '.tutorial': new Source.Views.List()
        });
      }
    });
    return Router;
  });

}).call(this);
