// Generated by CoffeeScript 1.6.2
(function() {
  define(["app"], function(app) {
    var Example;

    Example = app.module();
    Example.Model = Backbone.Model.extend({});
    Example.Collection = Backbone.Collection.extend({});
    Example.Router = Backbone.Router.extend({});
    Example.Views.Tutorial = Backbone.View.extend({
      template: "example"
    });
    return Example;
  });

}).call(this);
