// Generated by CoffeeScript 1.6.2
(function() {
  define(["app"], function(app) {
    var Home;

    Home = app.module();
    Home.Model = Backbone.Model.extend();
    Home.Collection = Backbone.Collection.extend({
      model: Home.Model
    });
    Home.Router = Backbone.Router.extend();
    Home.Views.Item = Backbone.View.extend({
      template: "home_item",
      tagName: "li",
      serialize: function() {
        return {
          name: this.model.get("name")
        };
      }
    });
    Home.Views.Tutorial = Backbone.View.extend({
      template: "home",
      initialize: function(init) {
        return this.collection = new Home.Collection(init);
      },
      beforeRender: function() {
        return this.collection.each(function(c) {
          return this.insertView("ul", new Home.Views.Item({
            model: c
          }));
        }, this);
      }
    });
    return Home;
  });

}).call(this);
